### ISSUE TITLE
environment variables within properties

### ISSUE THREAD

**Issue by benkuly** [coveooss/spring-boot-parameter-store-integration#11]
Would be nice, if one can use environment variables within properties.

Example:

`my.super.duper.secret: ${/my/parameter/store/<STAGE>/secret}`
The `<STAGE>` gets replaced by the environment variable `STAGE`, e.g. `production`.

**Comment by fredboutin** [comment]
You can also do this using nested properties!

`my.super.duper.secret: ${/my/parameter/store/${myapp.stage}/secret}`

If `myapp.stage` is an existing variable in the spring context, this will work. Just tested it.
