### ISSUE TITLE
Feature Request - Building Custom Paths

### ISSUE THREAD

**Issue by damianperera** [coveooss/spring-boot-parameter-store-integration#81]
# Background
We currently maintain configuration values for different environments which can be uniquely identified by the name of our active Spring profile.

e.g. The database URL is stored in the format `/app/<spring.application.name>/<spring.profiles.active>/DATABASE_URL` where `spring.profiles.active` can have one of the following values: `DEV`/`QA`/`STAG`/`PROD`.

# Problem
While we can hardcode `spring.application.name` into the placeholders, we have no way to specify a dynamic path parameter - however, this is supported in the official `spring-cloud-starter-aws-parameter-store-config` library (it constructs the path in the following format `/<aws.paramstore.prefix>/<aws.paramstore.name><aws.paramstore.profileSeparator><spring.profiles.active>/DATABASE_URL`).

We can't use the official lib because our legacy applications are targeted for Java `1.8.x` and running Spring Boot `2.0.3`. 

# Feature Request
Appreciate if you can provide a few configurable properties through which the library can build a custom path for the value instead of providing the entire path in the placeholder.

Current implementation:
```bash
database.url=${/app/test-service/DEV/DATABASE_URL}
```

Proposed implementation:
```bash
# preceding forward-slash denotes that this value is available in the Parameter Store
database.url=${/DATABASE_URL}
awsParameterStorePropertySource.prefix=/app
awsParameterStorePropertySource.includeAppName=true
awsParameterStorePropertySource.includeProfileName=true
```

The above parameters would indicate to the library to lookup `database.url` at  `/app/<spring.application.name>/<spring.profiles.active>/DATABASE_URL`.

**Comment by fredboutin** [comment]
From what I understand you have only one profile, so this can easily be done using placeholders like this:

`database.url=${/app/${spring.application.name}/${spring.profiles.active}/DATABASE_URL}`

I know it's a bit verbose to list all properties like this, but it's working with the current version and no need to hardcode. I just tried it with my app.

**Comment by damianperera** [comment]
@fredboutin thanks for your input - do default placeholder values work with this approach?

e.g. `database.url=${/app/${spring.application.name}/${spring.profiles.active}/DATABASE_URL:default_value}`

**Comment by fredboutin** [comment]
I don't think this works. The colon works in `@Value` annotation but not in the yaml itself. There are multiple ways to achieve this though, one way could be to have an application-local.yml with the default value and use the local profile in local. You could also use the default values in the `@Value` annotation of spring. Another way could be to put all default values in application.yml and override the variables using environment variables when running in cloud environments. There other ways, see Spring's documentation for more info: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config.
